"""Create or update the Azure AI Search index.

PowerShell bridge:
- The index definition is like a strongly typed schema object that gets sent to the
    service.
- Keeping the schema in code makes it easier to reason about search behavior the same
    way you would reason about a table definition in a script or provisioning file.
"""

from __future__ import annotations
from src.search.service import create_index_client
from src.config import AppConfig

from pathlib import Path
import sys

from azure.search.documents.indexes.models import (
    SearchIndex,
    SearchableField,
    SemanticConfiguration,
    SemanticField,
    SemanticPrioritizedFields,
    SemanticSearch,
    SimpleField,
    SearchFieldDataType,
)

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


def build_index_definition(settings: AppConfig) -> SearchIndex:
    """Build the Search index definition used for grounding.

    PowerShell bridge:
    - This is the data-shape contract for the retrieval layer.
    - If the document projection changes, this definition should change with it.
    """

    return SearchIndex(
        name=settings.azure_search_index_name,
        fields=[
            # The key field is the stable document identifier generated by the loader.
            SimpleField(name='id', type=SearchFieldDataType.String, key=True),
            SearchableField(name='source_type',
                            type=SearchFieldDataType.String, filterable=True),
            SearchableField(name='title', type=SearchFieldDataType.String),
            SearchableField(name='content', type=SearchFieldDataType.String),
            SimpleField(name='file_path',
                        type=SearchFieldDataType.String, filterable=True),
            SearchableField(name='heading', type=SearchFieldDataType.String),
            SearchableField(
                name='tags', type=SearchFieldDataType.String, filterable=True),
        ],
        semantic_search=SemanticSearch(
            configurations=[
                # Semantic ranking prioritizes the fields most useful for question answering.
                SemanticConfiguration(
                    name='default',
                    prioritized_fields=SemanticPrioritizedFields(
                        title_field=SemanticField(field_name='title'),
                        content_fields=[SemanticField(field_name='content')],
                        keywords_fields=[SemanticField(field_name='tags')],
                    ),
                )
            ]
        ),
    )


def main() -> None:
    """Read config, build the index definition, and send it to Azure AI Search.

    PowerShell bridge:
    - This is a command-style function, similar to a script that resolves settings and
      then performs one service operation.
    """

    settings = AppConfig.from_env()
    client = create_index_client(settings)
    index_definition = build_index_definition(settings)
    # `create_or_update_index` makes repeated runs safe, which is ideal for development.
    client.create_or_update_index(index=index_definition)
    print(f'Index {settings.azure_search_index_name} is ready.')


if __name__ == '__main__':
    # Keep the module executable so it can be used as a standalone setup command.
    main()
